# Generated by Django 3.2.7 on 2021-10-19 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('shift', models.IntegerField()),
                ('fte', models.FloatField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
