# Generated by Django 3.2.8 on 2021-10-31 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('shift', models.IntegerField()),
                ('fte', models.FloatField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
