# Generated by Django 3.2.8 on 2021-10-31 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='shift',
            new_name='shift_block',
        ),
    ]
