# Generated by Django 3.2.9 on 2021-11-07 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0004_auto_20211104_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContinuousSequenceConstraint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_id', models.IntegerField(choices=[(0, 'Off'), (1, 'Day'), (2, 'Second'), (3, 'Third')], default=0)),
                ('hard_min', models.IntegerField(default=0)),
                ('soft_min', models.IntegerField(default=0)),
                ('min_penalty', models.IntegerField(default=0)),
                ('soft_max', models.IntegerField(default=0)),
                ('hard_max', models.IntegerField(default=0)),
                ('max_penalty', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DailyCoverDemands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_shift_1', models.IntegerField(default=0)),
                ('num_shift_2', models.IntegerField(default=0)),
                ('num_shift_3', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeShiftPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_shift', models.IntegerField(choices=[(0, 'Off'), (1, 'Day'), (2, 'Second'), (3, 'Third')])),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.employee')),
            ],
        ),
        migrations.CreateModel(
            name='PenalizedTransitionsConstraint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_shift', models.IntegerField(choices=[(0, 'Off'), (1, 'Day'), (2, 'Second'), (3, 'Third')], default=0)),
                ('next_shift', models.IntegerField(choices=[(0, 'Off'), (1, 'Day'), (2, 'Second'), (3, 'Third')], default=0)),
                ('penalty', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyCoverDemands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_0', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monday', to='web_app.dailycoverdemands')),
                ('day_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tuesday', to='web_app.dailycoverdemands')),
                ('day_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wednesday', to='web_app.dailycoverdemands')),
                ('day_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thursday', to='web_app.dailycoverdemands')),
                ('day_4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friday', to='web_app.dailycoverdemands')),
                ('day_5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saturday', to='web_app.dailycoverdemands')),
                ('day_6', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sunday', to='web_app.dailycoverdemands')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklySumConstraint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_id', models.IntegerField(choices=[(0, 'Off'), (1, 'Day'), (2, 'Second'), (3, 'Third')], default=0)),
                ('hard_min', models.IntegerField(default=0)),
                ('soft_min', models.IntegerField(default=0)),
                ('min_penalty', models.IntegerField(default=0)),
                ('soft_max', models.IntegerField(default=0)),
                ('hard_max', models.IntegerField(default=0)),
                ('max_penalty', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='GlobalConstraints',
        ),
    ]
