# Generated by Django 3.2.9 on 2021-11-09 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0005_auto_20211107_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='fte',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='employee',
            name='shift_block',
            field=models.IntegerField(default=0),
        ),
    ]
