# Generated by Django 3.2.9 on 2021-11-12 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0006_auto_20211109_1837'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_weeks', models.IntegerField()),
                ('cs_shift_id', models.IntegerField()),
                ('cs_hard_min', models.IntegerField()),
                ('cs_soft_min', models.IntegerField()),
                ('cs_min_penalty', models.IntegerField()),
                ('cs_soft_max', models.IntegerField()),
                ('cs_hard_max', models.IntegerField()),
                ('cs_max_penalty', models.IntegerField()),
                ('ws_shift_id', models.IntegerField()),
                ('ws_hard_min', models.IntegerField()),
                ('ws_soft_min', models.IntegerField()),
                ('ws_min_penalty', models.IntegerField()),
                ('ws_soft_max', models.IntegerField()),
                ('ws_hard_max', models.IntegerField()),
                ('ws_max_penalty', models.IntegerField()),
                ('pt_previous_shift', models.IntegerField()),
                ('pt_next_shift', models.IntegerField()),
                ('pt_penalty', models.IntegerField()),
            ],
        ),
    ]
