# Generated by Django 3.2.9 on 2021-11-12 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0008_alter_reportresults_num_weeks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReportResults',
            new_name='ReportResult',
        ),
    ]
