# Generated by Django 3.2.9 on 2021-11-13 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0010_auto_20211112_1005'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverageByDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('by_day', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=0)),
                ('daily_cover_demands', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coverage_by_days', to='web_app.dailycoverdemands')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyCoverDemand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.ManyToManyField(related_name='weekly_cover_demands', through='web_app.CoverageByDay', to='web_app.DailyCoverDemands')),
            ],
        ),
        migrations.AlterField(
            model_name='continuoussequence',
            name='shift_id',
            field=models.IntegerField(choices=[(0, 'Off'), (1, 'Day'), (2, 'Second'), (3, 'Night')], default=0),
        ),
        migrations.AlterField(
            model_name='employeeshiftpreference',
            name='preferred_shift',
            field=models.IntegerField(choices=[(0, 'Off'), (1, 'Day'), (2, 'Second'), (3, 'Night')]),
        ),
        migrations.AlterField(
            model_name='penalizedtransitions',
            name='next_shift',
            field=models.IntegerField(choices=[(0, 'Off'), (1, 'Day'), (2, 'Second'), (3, 'Night')], default=0),
        ),
        migrations.AlterField(
            model_name='penalizedtransitions',
            name='previous_shift',
            field=models.IntegerField(choices=[(0, 'Off'), (1, 'Day'), (2, 'Second'), (3, 'Night')], default=0),
        ),
        migrations.AlterField(
            model_name='weeklysum',
            name='shift_id',
            field=models.IntegerField(choices=[(0, 'Off'), (1, 'Day'), (2, 'Second'), (3, 'Night')], default=0),
        ),
        migrations.DeleteModel(
            name='WeeklyCoverDemands',
        ),
        migrations.AddField(
            model_name='coveragebyday',
            name='weekly_cover_demand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coverage_by_days', to='web_app.weeklycoverdemand'),
        ),
    ]
