# Generated by Django 3.2.9 on 2021-11-26 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0012_auto_20211113_1815'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('employee', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ShiftAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_date', models.DateField()),
                ('assignment', models.IntegerField(default=0)),
                ('employee_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_assignments', to='web_app.employeeschedule')),
            ],
        ),
    ]
