# Generated by Django 3.2.9 on 2021-11-22 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0013_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='day_num',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='shift_assignment',
        ),
    ]
